# The three custom menus for CDR XMetaL.
menus = [
    dict(
        caption="&CDR",
        items=[
            dict(
                label="&New CDR Document",
                macro="New CDR Document",
                description="Create New CDR Document",
                icon=("CDR", 3, 9),
            ),
            dict(
                label="&Retrieve",
                macro="CDR Retrieve",
                description="Retrieve an existing CDR document by document ID",
                icon=("CDR", 4, 7),
            ),
            dict(
                label="S&earch",
                macro="CDR Search",
                description="Search for CDR Document",
                icon=("CDR", 3, 1),
            ),
            dict(
                label="&Advanced Search",
                macro="CDR Advanced Search",
                description="Launch browser-based CDR search form",
                icon=("CDR", 3, 2),
            ),
            dict(
                label="Prin&t",
                macro="Print",
                description="Print the current document",
                icon=("CDR", 1, 10),
                new_group=True,
            ),
            dict(
                label="&Validate",
                macro="CDR Validate",
                description="Validate the current CDR document",
                icon=("CDR", 4, 1),
                new_group=True,
            ),
            dict(
                label="&Save",
                macro="CDR Save",
                description="Save the current CDR document",
                icon=("CDR", 3, 10),
            ),
            dict(
                label="&Unlock",
                macro="CDR Check In",
                description="Unlock the current CDR document",
                icon=("CDR", 6, 6),
            ),
            dict(
                label="Ad&ministrative Subsystem",
                macro="Administrative Subsystem",
                description="Invoke the web-based CDR Administration menu",
                icon=("Databases (Custom)", 2, 10),
                new_group=True,
            ),
            dict(
                label="CDR &Help",
                macro="CDR Help",
                description="Launch the CDR Help System",
                icon=("CDR", 4, 2),
                new_group=True,
            ),
        ],
    ),
    dict(
        caption="CDR &Styles",
        items=[
            dict(
                label="&Insertion",
                macro="Insertion",
                description="Add Insertion markup",
                icon=("CDR", 1, 6),
            ),
            dict(
                label="&Deletion",
                macro="Deletion",
                description="Add Deletion markup",
                icon=("CDR", 1, 7),
            ),
            dict(
                label="Itemized &List",
                macro="Itemized List",
                description="Insert itemized list",
                icon=("CDR", 6, 1),
                new_group=True,
            ),
            dict(
                label="&Ordered List",
                macro="Ordered List",
                description="Insert ordered list",
                icon=("CDR", 6, 2),
            ),
            dict(
                label="&Table",
                macro="Table",
                description="Invoke the XMetaL table wizard",
                icon=("CDR", 5, 9),
            ),
            dict(
                label="D&ate",
                macro="Insert Current Date",
                description="Insert the current date",
                icon=("CDR", 6, 8),
            ),
            dict(
                label="&User",
                macro="Insert User ID",
                description="Insert the current user ID",
                icon=("CDR", 5, 10),
            ),
            dict(
                label="D&rug Name",
                macro="Insert DrugName Element",
                description="Add DrugName element tags to the current selection",
                new_group=True,
            ),
            dict(
                label="&Foreign Word",
                macro="Insert ForeignWord Element",
                description="Add ForeignWord element tags to the current selection",
            ),
            dict(
                label="&Gene Name",
                macro="Insert GeneName Element",
                description="Add GeneName element tags to the current selection",
            ),
            dict(
                label="S&cientific Name",
                macro="Insert ScientificName Element",
                description="Add ScientificName element tags to the current selection",
            ),
            dict(
                label="&Emphasis",
                macro="Insert Emphasis Element",
                description="Add Add Emphasis element tags to the current selection",
                new_group=True,
            ),
            dict(
                label="&Strong",
                macro="Insert Strong Element",
                description="Add Strong element tags to the current selection",
            ),
            dict(
                label="Su&bscript",
                macro="Insert Subscript Element",
                description="Add Subscript element tags to the current selection",
            ),
            dict(
                label="Su&perscript",
                macro="Insert Superscript Element",
                description="Add Superscript element tags to the current selection",
            ),
        ],
    ),
    dict(
        caption="CDR &Markup",
        items=[
            dict(
                label="Find &Next Change",
                macro="Find Next",
                description="Find next markup change",
                icon=("CDR", 1, 8),
            ),
            dict(
                label="&Accept Change",
                macro="Accept Change",
                description="Accept current markup change",
                icon=("CDR", 2, 6),
                new_group=True,
            ),
            dict(
                label="A&ccept All Changes",
                macro="Accept Changes",
                description="Accept all markup changes",
                icon=("CDR", 2, 7),
            ),
            dict(
                label="&Reject Change",
                macro="Reject Change",
                description="Reject current markup change",
                icon=("CDR", 2, 8),
            ),
            dict(
                label="&Back Out Rejected Changes",
                macro="Back Out Rejected Markup",
                description="Back out rejected tracked changes",
                icon=("Design (Custom)", 4, 10),
            ),
            dict(
                label="R&eview All Changes",
                macro="Review Markup",
                description="Accept or reject changes",
            ),
        ],
    ),
]

# Custom toolbars for CDR XMetaL.
toolbars = [
    dict(
        name="CDR",
        buttons=[
            dict(
                macro="New CDR Document",
                tooltip="New CDR Document",
                description="Create new CDR document",
                icon=("CDR",  3,  9),
            ),
            dict(
                macro="CDR Retrieve",
                tooltip="Retrieve",
                description="Retrieve existing CDR document with document ID",
                icon=("CDR",  4,  7),
            ),
            dict(
                macro="CDR Search",
                tooltip="Search",
                description="Search for an existing CDR document",
                icon=("CDR",  3,  1),
            ),
            dict(
                macro="CDR Advanced Search",
                tooltip="Advanced Search",
                description="Launch browser-based CDR search form",
                icon=("CDR",  3,  2),
            ),
            dict(
                macro="Document History Report",
                tooltip="Document History",
                description="Show Document History",
                icon=("CDR",  4,  8),
                new_group=True,
            ),
            dict(
                macro="Audit Trail Report",
                tooltip="Audit Trail",
                description="Show Audit Trail",
                icon=("Annotations (Custom)",  1,  6),
            ),
            dict(
                macro="Show Checked Out Docs",
                tooltip="Checked Out",
                description="Show Checked Out Docs",
                icon=("CDR",  1,  1),
            ),
            dict(
                macro="Print",
                tooltip="Print",
                description="Print the current document",
                icon=("CDR",  1,  10),
            ),
            dict(
                macro="CDR Validate",
                tooltip="Validate",
                description="Validate the current CDR document",
                icon=("CDR",  4,  1),
            ),
            dict(
                macro="CDR Save",
                tooltip="Save",
                description="Save the current document",
                icon=("CDR",  3,  10),
            ),
            dict(
                macro="Administrative Subsystem",
                tooltip="Administrative Subsystem",
                description="Invoke the web-based CDR Administration menu",
                icon=("Databases (Custom)",  2,  10),
            ),
            dict(
                macro="Insertion",
                tooltip="Insertion",
                description="Add Insertion markup",
                icon=("CDR",  1,  6),
                new_group=True,
            ),
            dict(
                macro="Deletion",
                tooltip="Deletion",
                description="Add Deletion markup",
                icon=("CDR",  1,  7),
            ),
            dict(
                macro="Find Next",
                tooltip="Find Next",
                description="Find Next Change",
                icon=("CDR",  1,  8),
            ),
            dict(
                macro="Accept Change",
                tooltip="Accept Change",
                description="Accept Change",
                icon=("CDR",  2,  6),
            ),
            dict(
                macro="Reject Change",
                tooltip="Reject Change",
                description="Reject Change",
                icon=("CDR",  2,  8),
            ),
            dict(
                macro="Navigate Comments",
                tooltip="Find Comments",
                description="Find Comments",
                icon=("CDR2",  3,  3),
                new_group=True,
            ),
            dict(
                macro="Itemized List",
                tooltip="Itemized List",
                description="Insert itemized list",
                icon=("CDR",  6,  1),
                new_group=True,
            ),
            dict(
                macro="Ordered List",
                tooltip="Ordered List",
                description="Insert ordered list",
                icon=("CDR",  6,  2),
            ),
            dict(
                macro="Insert Current Date",
                tooltip="Current Date",
                description="Insert Current Date",
                icon=("CDR",  6,  8),
            ),
            dict(
                macro="Insert User ID",
                tooltip="User Name",
                description="Insert User ID",
                icon=("CDR",  5,  10),
            ),
            dict(
                macro="Find Private Use Chars",
                tooltip="Find Private Use Unicode Characters",
                description="Find Private Use Unicode Characters",
                icon=("General (Custom)",  4,  10),
                new_group=True,
            ),
            dict(
                macro="CDR Help",
                tooltip="CDR Help",
                description="Launch the CDR Help System",
                icon=("CDR",  4,  2),
                new_group=True,
            ),
        ],
    ),
    dict(
        name="CDR Symbols",
        buttons=[
            dict(
                macro="SC Up",
                tooltip="Up",
                description="Up",
                icon=("CDR", 7, 2),
            ),
            dict(
                macro="SC Down",
                tooltip="Down",
                description="Down",
                icon=("CDR", 7, 3),
            ),
            dict(
                macro="SC Right",
                tooltip="Right",
                description="Right",
                icon=("CDR", 7, 5),
            ),
            dict(
                macro="SC Left",
                tooltip="Left",
                description="Left",
                icon=("CDR", 7, 4),
            ),
            dict(
                macro="SC alpha",
                tooltip="alpha",
                description="alpha",
                icon=("CDR", 7, 6),
            ),
            dict(
                macro="SC beta",
                tooltip="beta",
                description="beta",
                icon=("CDR", 7, 7),
            ),
            dict(
                macro="SC gamma",
                tooltip="gamma",
                description="gamma",
                icon=("CDR", 7, 8),
            ),
            dict(
                macro="SC delta",
                tooltip="delta",
                description="delta",
                icon=("CDR", 7, 9),
            ),
            dict(
                macro="SC mu",
                tooltip="mu",
                description="mu",
                icon=("CDR", 7, 10),
            ),
            dict(
                macro="SC le",
                tooltip="</=",
                description="</=",
                icon=("CDR", 8, 1),
            ),
            dict(
                macro="SC ge",
                tooltip=">/=",
                description=">/=",
                icon=("CDR", 8, 2),
            ),
            dict(
                macro="SC copy",
                tooltip="(C)",
                description="(C)",
                icon=("CDR", 8, 3),
            ),
            dict(
                macro="SC reg",
                tooltip="(R)",
                description="(R)",
                icon=("CDR", 8, 4),
            ),
            dict(
                macro="SC TM",
                tooltip="TM",
                description="TM",
                icon=("CDR", 8, 5),
            ),
            dict(
                macro="SC deg",
                tooltip="Degree",
                description="Degree",
                icon=("CDR", 8, 6),
            ),
            dict(
                macro="SC cross",
                tooltip="Dagger",
                description="Dagger",
                icon=("CDR", 8, 7),
            ),
            dict(
                macro="SC dblx",
                tooltip="DDagger",
                description="DDagger",
                icon=("CDR", 8, 8),
            ),
            dict(
                macro="SC mdash",
                tooltip="Em Dash",
                description="Em dash",
                icon=("CDR", 8, 9),
            ),
            dict(
                macro="SC plusmin",
                tooltip="+/-",
                description="+/-",
                icon=("CDR", 8, 10),
            ),
            dict(
                macro="SC lapos",
                tooltip="LApos",
                description="LApos",
                icon=("CDR2", 1, 1),
            ),
            dict(
                macro="SC rapos",
                tooltip="RApos",
                description="RApos",
                icon=("CDR2", 1, 2),
            ),
            dict(
                macro="SC lquot",
                tooltip="LQuot",
                description="LQuot",
                icon=("CDR2", 1, 3),
            ),
            dict(
                macro="SC rquot",
                tooltip="RQuot",
                description="RQuot",
                icon=("CDR2", 1, 4),
            ),
            dict(
                macro="SC quarter",
                tooltip="1/4",
                description="1/4",
                icon=("CDR2", 1, 5),
            ),
            dict(
                macro="SC half",
                tooltip="1/2",
                description="1/2",
                icon=("CDR2", 1, 6),
            ),
            dict(
                macro="SC 3quart",
                tooltip="3/4",
                description="3/4",
                icon=("CDR2", 1, 7),
            ),
            dict(
                macro="SC nbsp",
                tooltip="NBSP",
                description="NBSP",
                icon=("CDR2", 1, 8),
            ),
        ],
    ),
    dict(
        name="CDR Summary",
        doctype="Summary",
        buttons=[
            dict(
                macro="New Summary Section",
                tooltip="New Section",
                description="Insert new SummarySection",
                icon=("General (Custom)",  5,  8),
            ),
            dict(
                macro="Insert CitationLink",
                tooltip="Citation Link",
                description="Insert Citation Link",
                icon=("CDR",  6,  9),
                new_group=True,
            ),
            dict(
                macro="Insert DateLastModified",
                tooltip="DateLastModified",
                description="Insert DateLastModified",
                icon=("CDR",  5,  2),
            ),
            dict(
                macro="Bold Underline Report",
                tooltip="HP B/U",
                description="Bold Underline Report",
                icon=("CDR",  2,  3),
                new_group=True,
            ),
            dict(
                macro="Redline Strikeout Report",
                tooltip="HP RLSO",
                description="Redline Strikeout Report",
                icon=("CDR",  2,  4),
            ),
            dict(
                macro="Patient Summary BU QC Report",
                tooltip="PT B/U",
                description="Patient Summary BU QC Report",
                icon=("CDR2",  2,  1),
            ),
            dict(
                macro="Patient Summary RS QC Report",
                tooltip="PT RLSO",
                description="Patient Summary RS QC Report",
                icon=("CDR",  3,  5),
            ),
            dict(
                macro="Publish Preview",
                tooltip="Publish Preview",
                description="Publish Preview",
                icon=("Structure (Custom)",  1,  8),
            ),
            dict(
                macro="Back Out Rejected Markup",
                tooltip="Back Out Rejected Changes",
                description="Back out rejected tracked changes",
                icon=("Design (Custom)",  4,  10),
            ),
            dict(
                macro="Find Next Advisory Board Markup",
                tooltip="Find Next Advisory Board Markup",
                description="Find next Advisory Board markup",
                icon=("Databases (Custom)",  7,  4),
                new_group=True,
            ),
            dict(
                macro="View SVPC Docs",
                tooltip="View SVPC Docs",
                description="View SVPC Documents",
                icon=("CDR",  5,  1),
            ),
            dict(
                macro="Edit SVPC Docs",
                tooltip="Edit SVPC Docs",
                description="Edit SVPC Documents",
                icon=("CDR",  5,  4),
            ),
            dict(
                macro="Open Patient Summary",
                tooltip="Patient",
                description="Open patient version of this summary",
                icon=("CDR2",  3,  1),
                new_group=True,
            ),
            dict(
                macro="Open HP Summary",
                tooltip="HP",
                description="Open health professional version of this summary",
                icon=("CDR2",  3,  2),
            ),
            dict(
                macro="Open Original English Summary",
                tooltip="English",
                description="Open original English summary of which this is a translation",
                icon=("CDR2",  2,  4),
                new_group=True,
            ),
            dict(
                macro="Open Translated Summary",
                tooltip="Spanish",
                description="Open Spanish translation of this summary",
                icon=("CDR2",  2,  3),
            ),
            dict(
                macro="Translation Job",
                tooltip="Translation Job",
                description="Add/edit translation job for this summary",
                icon=("Databases (Custom)",  4,  1),
                new_group=True,
            ),
            dict(
                macro="Translation Job Queue",
                tooltip="Translation Job Queue",
                description="Open interface for managing translation job queue",
                icon=("Databases (Custom)",  4,  8),
            ),
            dict(
                macro="Translation Job Workflow Report",
                tooltip="Translation Job Workflow Report",
                description="Request a report on the translation job queue",
                icon=("Databases (Custom)",  6,  6),
            ),
            dict(
                macro="Glossify Document",
                tooltip="Glossify Document",
                description="Glossify Document",
                icon=("General (Custom)",  5,  9),
                new_group=True,
            ),
            dict(
                macro="Glossify Document (dig)",
                tooltip="Glossify Document (include all sections in markup)",
                description="Glossify Document (include all sections in markup)",
                icon=("General (Custom)",  5,  7),
            ),
            dict(
                macro="Glossify Genetics Terms",
                tooltip="Glossify Genetics Terms",
                description="Glossify Genetics Terms",
                icon=("General (Custom)",  7,  4),
            ),
            dict(
                macro="Glossify Genetics Terms (include markup)",
                tooltip="Glossify Genetics Terms (include markup)",
                description="Glossify Genetics Terms (include markup)",
                icon=("General (Custom)",  7,  8),
            ),
            dict(
                macro="Glossify Patient Terms",
                tooltip="Glossify Patient Terms",
                description="Glossify Patient Terms",
                icon=("General (Custom)",  7,  4),
            ),
            dict(
                macro="Glossify Patient Terms (include markup)",
                tooltip="Glossify Patient Terms (include markup)",
                description="Glossify Patient Terms (include markup)",
                icon=("General (Custom)",  7,  8),
            ),
            dict(
                macro="Insert TypeOfChange",
                tooltip="Insert Type of Summary Change",
                description="Insert Type of Summary Change",
                icon=("Revisions (Custom)",  2,  5),
            ),
        ],
    ),
    dict(
        name="CDR Person",
        doctype="Person",
        buttons=[
            dict(
                macro="Generate QC Report",
                tooltip="QC Report",
                description="Generate QC Report",
                icon=("CDR",  3,  4),
            ),
            dict(
                macro="Linked Docs Report",
                tooltip="Linked Docs",
                description="Launch Linked Docs Report",
                icon=("Integration (Custom)",  3,  9),
            ),
            dict(
                macro="Open Board Member Doc",
                tooltip="Open Board Member Doc",
                description="Open Board Member Doc",
                icon=("Databases (Custom)",  7,  1),
            ),
        ],
    ),
    dict(
        name="CDR Organization",
        doctype="Organization",
        buttons=[
            dict(
                macro="Generate QC Report",
                tooltip="QC Report",
                description="Generate QC Report",
                icon=("CDR",  3,  4),
            ),
            dict(
                macro="Linked Docs Report",
                tooltip="Linked Docs",
                description="Launch Linked Docs Report",
                icon=("Integration (Custom)",  3,  9),
            ),
        ],
    ),
    dict(
        name="CDR Term",
        doctype="Term",
        buttons=[
            dict(
                macro="Term Hierarchy",
                tooltip="Hierarchy",
                description="View Hierarchy",
                icon=("Databases (Custom)",  6,  3),
            ),
            dict(
                macro="Generate QC Report",
                tooltip="QC Report",
                description="Generate QC Report",
                icon=("CDR",  3,  4),
                new_group=True,
            ),
        ],
    ),
    dict(
        name="CDR Glossary Term Concept",
        doctype="GlossaryTermConcept",
        buttons=[
            dict(
                macro="Full Concept QC Report",
                tooltip="Full Concept QC Report",
                description="Generate Full QC Report",
                icon=("CDR",  4,  3),
            ),
            dict(
                macro="Generate QC Report",
                tooltip="GT Concept QC Report",
                description="Generate QC Report",
                icon=("CDR",  3,  4),
            ),
            dict(
                macro="Show Glossary Term Names",
                tooltip="Term Names",
                description="Show Glossary Term Names",
                icon=("Integration (Custom)",  7,  1),
            ),
            dict(
                macro="Make Glossary Term Name Doc",
                tooltip="Glossary Term",
                description="Create Term Name Document",
                icon=("CDR2",  2,  10),
            ),
            dict(
                macro="View Glossary Term Name Docs",
                tooltip="View GT Name Docs",
                description="View Term Name Documents",
                icon=("Integration (Custom)",  3,  9),
            ),
            dict(
                macro="Edit Glossary Term Name Docs",
                tooltip="Edit GT Name Docs",
                description="Edit Term Name Documents",
                icon=("CDR",  5,  3),
            ),
            dict(
                macro="Glossary Translation Job",
                tooltip="Add Translation Job",
                description="Add/edit translation job for this Glossary document",
                icon=("Databases (Custom)",  4,  1),
                new_group=True,
            ),
            dict(
                macro="Glossary Translation Job Queue",
                tooltip="Translation Job Queue",
                description="Open interface for managing translation job queue",
                icon=("Databases (Custom)",  4,  8),
            ),
            dict(
                macro="Glossary Translation Job Workflow Report",
                tooltip="Translation Job Workflow Report",
                description="Request a report on the translation job queue",
                icon=("Databases (Custom)",  6,  6),
            ),
        ],
    ),
    dict(
        name="CDR Glossary Term Name",
        doctype="GlossaryTermName",
        buttons=[
            dict(
                macro="TermName with Concept QC Report",
                tooltip="GT Name/Concept QC",
                description="Generate QC Report",
                icon=("CDR",  3,  8),
            ),
            dict(
                macro="Generate QC Report",
                tooltip="GT Name QC Report",
                description="Generate QC Report",
                icon=("CDR",  3,  4),
            ),
            dict(
                macro="View Linked Glossary Term Concept Doc",
                tooltip="View GT Concept",
                description="View Concept Document",
                icon=("Integration (Custom)",  3,  9),
            ),
            dict(
                macro="Edit Linked Glossary Term Concept Doc",
                tooltip="Edit GT Concept",
                description="Edit Concept Document",
                icon=("CDR",  5,  3),
            ),
            dict(
                macro="Publish Preview",
                tooltip="Publish Preview",
                description="Publish Preview",
                icon=("Structure (Custom)",  1,  8),
            ),
            dict(
                macro="Glossary Phrase Search",
                tooltip="Glossary Phrase Search",
                description="Report on matching GlossaryTermName phrases",
                icon=("Revisions (Custom)",  2,  2),
            ),
            dict(
                macro="Glossary Translation Job",
                tooltip="Add Translation Job",
                description="Add/edit translation job for this Glossary document",
                icon=("Databases (Custom)",  4,  1),
                new_group=True,
            ),
            dict(
                macro="Glossary Translation Job Queue",
                tooltip="Translation Job Queue",
                description="Open interface for managing translation job queue",
                icon=("Databases (Custom)",  4,  8),
            ),
            dict(
                macro="Glossary Translation Job Workflow Report",
                tooltip="Translation Job Workflow Report",
                description="Request a report on the translation job queue",
                icon=("Databases (Custom)",  6,  6),
            ),
        ],
    ),
    dict(
        name="CDR Drug Info",
        doctype="DrugInformationSummary",
        buttons=[
            dict(
                macro="DrugInfo QC Report",
                tooltip="QC Report",
                description="Generate QC Report",
                icon=("CDR",  3,  4),
            ),
            dict(
                macro="Publish Preview",
                tooltip="Publish Preview",
                description="Publish Preview",
                icon=("Structure (Custom)",  1,  8),
            ),
        ],
    ),
    dict(
        name="CDR Licensee",
        doctype="Licensee",
        buttons=[
            dict(
                macro="Licensee QC Report",
                tooltip="Licensee QC Report",
                description="Licensee QC Report",
                icon=("CDR",  3,  4),
            ),
        ],
    ),
    dict(
        name="CDR Country",
        doctype="Country",
        buttons=[
            dict(
                macro="Country QC Report",
                tooltip="QC Report",
                description="Country QC Report",
                icon=("CDR",  3,  4),
            ),
        ],
    ),
    dict(
        name="CDR Citation",
        doctype="Citation",
        buttons=[
            dict(
                macro="Search PubMed",
                tooltip="PubMed",
                description="Search PubMed",
                icon=("CDR",  3,  3),
            ),
            dict(
                macro="Generate QC Report",
                tooltip="QC Report",
                description="Generate QC Report",
                icon=("CDR",  3,  4),
                new_group=True,
            ),
            dict(
                macro="Make Citation Supplementary Info Doc",
                tooltip="Create SupplementaryInfo doc",
                description="Create SupplementaryInfo document",
                icon=("CDR2",  2,  6),
                new_group=True,
            ),
        ],
    ),
    dict(
        name="CDR Miscellaneous Document",
        doctype="MiscellaneousDocument",
        buttons=[
            dict(
                macro="Generate QC Report",
                tooltip="QC Report",
                description="Generate QC Report",
                icon=("CDR",  3,  4),
            ),
        ],
    ),
    dict(
        name="CDR Mailer",
        docctype="Mailer",
        buttons=[
            dict(
                macro="Insert Mailer Response",
                tooltip="Response",
                description="Insert Mailer Response",
                icon=("CDR",  6,  5),
            ),
        ],
    ),
    dict(
        name="CDR TermSet",
        doctype="TermSet",
        buttons=[
            dict(
                macro="TermSet QC Report",
                tooltip="QC Report",
                description="Generate QC Report",
                icon=("CDR",  3,  4),
                new_group=True,
            ),
        ],
    ),
    dict(
        name="CDR PDQBoardMemberInfo",
        doctype="PDQBoardMemberInfo",
        buttons=[
            dict(
                macro="Generate QC Report",
                tooltip="QC Report",
                description="Generate QC Report",
                icon=("CDR",  3,  4),
            ),
            dict(
                macro="Open Person Doc For Board Member",
                tooltip="Open Person Doc For Board Member",
                description="Open Person Doc For Board Member",
                icon=("Databases (Custom)",  7,  3),
            ),
        ],
    ),
    dict(
        name="CDR Media Document",
        doctype="Media",
        buttons=[
            dict(
                macro="Show Doc Blob",
                tooltip="Launch Media File",
                description="Launch Media File",
                icon=("Design (Custom)",  2,  3),
            ),
            dict(
                macro="Generate QC Report",
                tooltip="Media QC Report",
                description="Generate QC Report",
                icon=("CDR2",  1,  10),
            ),
            dict(
                macro="Media Side-by-Side Report",
                tooltip="Show English-Spanish Images and Labels",
                description="Generate English-Spanish Side-by-Side Report",
                icon=("Structure (Custom)",  5,  9),
            ),
            dict(
                macro="Clone Doc",
                tooltip="Clone Document",
                description="Clone Media Document",
                icon=("CDR2",  2,  5),
                new_group=True,
            ),
            dict(
                macro="Open Original English Media Doc",
                tooltip="English",
                description="Open original English media doc of which this is a translation",
                icon=("CDR2",  2,  4),
                new_group=True,
            ),
            dict(
                macro="Open Translated Media Doc",
                tooltip="Spanish",
                description="Open Spanish translation of this media doc",
                icon=("CDR2",  2,  3),
            ),
            dict(
                macro="Media Translation Job",
                tooltip="Add Translation Job",
                description="Add/edit translation job for this Media document",
                icon=("Databases (Custom)",  4,  1),
                new_group=True,
            ),
            dict(
                macro="Media Translation Job Queue",
                tooltip="Translation Job Queue",
                description="Open interface for managing translation job queue",
                icon=("Databases (Custom)",  4,  8),
            ),
            dict(
                macro="Media Translation Job Workflow Report",
                tooltip="Translation Job Workflow Report",
                description="Request a report on the translation job queue",
                icon=("Databases (Custom)",  6,  6),
            ),
        ],
    ),
    dict(
        name="CDR Supplementary Info Document",
        doctype="SupplementaryInfo",
        buttons=[
            dict(
                macro="Show Doc Blob",
                tooltip="Launch Object File",
                description="Launch Object File",
                icon=("Databases (Custom)",  2,  6),
            ),
            dict(
                macro="Clone Doc",
                tooltip="Clone Document",
                description="Clone SupplementaryInfo Document",
                icon=("CDR2",  2,  5),
                new_group=True,
            ),
        ],
    ),
]
