/*
 * $Id: ServerSettingsDlg.h,v 1.1.1.1 2005-11-08 21:30:22 bkline Exp $
 *
 * Interface for object used to track and manipulate values for
 * connecting with the CDR servers.
 *
 * $Log: not supported by cvs2svn $
 */
#pragma once
#include "afxwin.h"

// Forward reference.
struct ServerSettings;

/*
 * Object for dialog window used to display and modify the values
 * for connecting with the CDR servers.  CString data members are
 * used to store each of the following:
 *
 *    - DNS name for the CDR service's server
 *    - port on which this server listens (usually 2019)
 *    - DNS name for the SOAP server (usually same as CDR server)
 *    - port on which this server listens (usually 80)
 *
 * There is a set of these four values for each of the following
 * machines:
 *
 *    - the production machine (e.g., bach.nci.nih.gov)
 *    - the test machine (e.g., franck.nci.nih.gov)
 *    - the development machine (e.g., mahler.nci.nih.gov)
 *
 * The original for this file was generated by a Visual Studio MFC
 * wizard.  Don't mess with the macros unless you really know what
 * you're doing.
 */
class ServerSettingsDlg : public CDialog {
    
	DECLARE_DYNAMIC(ServerSettingsDlg)

public:
	ServerSettingsDlg(ServerSettings*, CWnd* pParent = NULL); 
	virtual ~ServerSettingsDlg();

// Dialog Data
	enum { IDD = IDD_SERVER_SETTINGS };

protected:
	virtual void DoDataExchange(CDataExchange* pDX);    // DDX/DDV support

	DECLARE_MESSAGE_MAP()
public:
    CString prodUpdateServer;
    CString prodUpdatePort;
    CString prodCdrServer;
    CString prodCdrPort;
    CString testUpdateServer;
    CString testUpdatePort;
    CString testCdrServer;
    CString testCdrPort;
    CString devUpdateServer;
    CString devUpdatePort;
    CString devCdrServer;
    CString devCdrPort;
    ServerSettings* ss;
    afx_msg void OnBnClickedOk();
    virtual BOOL OnInitDialog();
};
