/*
 * Interface for the progress window's object.  There's a method for
 * bumping up the current position of the progress bar, and another
 * for setting the initial values for the bar.  Mostly generated by
 * a Visual Studio MFC wizard.  Don't touch the macros unless you
 * really know what you're doing.
 */
#pragma once
#include "afxcmn.h"


// CdrProgressDlg dialog

class CdrProgressDlg : public CDialog {
    
	DECLARE_DYNAMIC(CdrProgressDlg)

public:
	CdrProgressDlg(CWnd* pParent = NULL);   // standard constructor
	virtual ~CdrProgressDlg();

// Dialog Data
	enum { IDD = IDD_PROGRESS_BAR };

protected:
	virtual void DoDataExchange(CDataExchange* pDX);    // DDX/DDV support

	DECLARE_MESSAGE_MAP()
public:
    CProgressCtrl progressBar;
    void Init();
    void Advance() { progressBar.StepIt(); }
};
